# Generated by Django 3.0.8 on 2020-07-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('update_post', 'Can update a post'), ('edit a post', 'Can edit a post'))},
        ),
    ]
